# Generated by Django 4.1.7 on 2023-03-31 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = []
